Added VSCODE workspace and added formatting in CI
torfmaster/ribzip2 pull request #13
Opened 2022-01-30 09:49 UTC by DipayanP007

Solves #11 
* Created a VScode workspace file 
* set "format on save" as default setting
* Modified CI to run `cargo fmt --all`

2022-01-31 07:54 UTC, torfmaster requested changes
Thank you for your PR! I have commented one minor topic but I am otherwise happy!

2022-01-31 07:54 UTC, torfmaster commented on .github/workflows/build.yml
> +           cargo fmt --all
I think you want to fail the CI, i.e. do a `cargo fmt --all -- --check`.

2022-01-31 09:37 UTC, DipayanP007 commented
Hey @torfmaster I made the changes kindly review it

2022-01-31 10:42 UTC, torfmaster commented
@DipayanP007: The checks have failed (which shows that your change work :tada: )can you please format the code and check in the changes?

2022-02-01 18:18 UTC, torfmaster commented
ping @DipayanP007

2022-02-01 18:24 UTC, DipayanP007 commented
Hey @torfmaster sorry I was a bit busy. Actually I don't have knowledge regarding Rust programming.

2022-02-01 19:01 UTC, torfmaster commented
No worries. You just need to run `cargo fmt --all` and commit+push the result, this will fix the formatting errors.

2022-02-02 13:33 UTC, DipayanP007 commented
Hey @torfmaster I made the changes and pushed it. Give it a look

2022-02-02 14:38 UTC, torfmaster commented
Thank you for your contribution!

2022-02-02 14:38 UTC, merged